### ISSUE TITLE
"Remember to partition in Disk Utility first!"

### ISSUE THREAD

**Issue by MotorCityCobra** [foxlet/macOS-Simple-KVM#139]
What does this mean exactly? In another tutorial it said to "erase" some drive in order to install it. I have no idea what is to be partitioned or erased. My macOS Base System is grey and cannot be partitioned or erased. Can somebody clue me in? All I see in the disk utility is the grey macOS, a disk about 200MB and the 64GB. Does anybody on the world wide web explain what should be done, what I'm supposed to see here, what I'm supposed to do with this?

**Comment by shxdow** [comment]
I'm too wondering what does this mean

**Comment by CuriousTommy** [comment]
Partition is just a fancy way of saying that the hard drive need to be erased and formatted so that macOS can install the system files on it.

> a disk about 200MB

This is a special boot disk (`ESP.qow2`) that is used to help boot up macOS. Formatting this drive will prevent you from being able to boot up macOS.

> the 64GB

Remember that command you ran a while ago?
```
qemu-img create -f qcow2 MyDisk.qcow2 64G
```
This is the hard drive you created to install macOS into. General rule of thumb is to pick the hard drive with the largest storage.
