### ISSUE TITLE
iCloud - Account Limit Reached

### ISSUE THREAD

**Issue by acollazog11** [foxlet/macOS-Simple-KVM#211]
I'm having this problem when i try to start using iCloud: "Account Limit Reached"
How can i solve this?

Any help would be appreciated. Thank you.

![iCloud](https://user-images.githubusercontent.com/16126431/81092140-8ee8fa00-8ed6-11ea-8386-a2d5b102b4a7.png)

**Comment by tanish-m** [comment]
Apple only allows 5 Apple IDs to be created per serial number per year, and since this isn't a genuine computer, Apple doesn't allow you to make any. The only workaround is to change your serial number, and that could be done by this video:
https://www.youtube.com/watch?v=3xn9CpRjkf4
I've used this video and I'm able to create Apple IDs since I used a "fake" serial number, but for me, iMessage and FaceTime aren't working. This is a hit or miss type of thing, so good luck.

**Comment by rgvxlens** [comment]
Have a look at [issue number 33](https://github.com/foxlet/macOS-Simple-KVM/issues/33), might just solve your problem.

**Comment by acollazog11** [comment]
Thanks @tanish-m it worked for me, it's just what i was looking for

Thanks a lot!!!

**Comment by smutao** [comment]
So this means all installed VMs from this method have the same serial number in the system info?
