### ISSUE TITLE
Failed To Initialize KVM: No such file or directory 

### ISSUE THREAD

**Issue by BlockArchitech** [foxlet/macOS-Simple-KVM#252]
When i try to run basic.sh, i get this error:

`Could Not Access KVM kernel module: No Such file or directory.
qemu-system-x86_64: Failed to Initialize KVM: No such file or directory.`

Any help appreciated.

**Comment by eniac111** [comment]
`apt-get install qemu-kvm` for Ubuntu. The package is not in the documentation.

**Comment by manipreet** [comment]
Tried this doesn't help. i have checked the location /usr/bin/qemu-system-x86_64 and there is no such directory.
Instead i have a file in /usr/libexec/qemu-kvm. 
I am running CentOS 8

**Comment by narenkpai** [comment]
I am on manjaro and the same thing is happening to me.

**Comment by Ida-Ida** [comment]
Had the same issue on Ubuntu. 
Cause (for me): **"virtualization" was disabled in my BIOS**. You can check this by running `lsmod | grep kvm` - if it shows smth like `kvm        598016  0` it's disabled. Otherwise it should additionally show the `kvm_amd` or `kvm_intel` module

1. enable "virtulaization" or however it's called in your BIOS
2. try again. Same error? - You may need to load your kvm modules
`$ sudo modprobe kvm`
`$ sudo modprobe kvm_intel ` (..`kvm_amd` for amd-CPUs)
If errors appear when loading the modules: `dmesg | grep kvm` 

I found this information here (only German): https://wiki.ubuntuusers.de/KVM/

**Comment by narenkpai** [comment]
thanks,  for me virtualization was disabled

**Comment by nxtkaixathebest** [comment]
sigh, Virtualization is enabled but still i cant
