### ISSUE TITLE
Passing through intel integrated GPU

### ISSUE THREAD

**Issue by hericiumvevo** [foxlet/macOS-Simple-KVM#376]
Hello, is there an option to pass my i5-6400 integrated GPU?

**Comment by ghost** [comment]
Try using virt-manager

**Comment by Jerit3787** [comment]
There is no way you can passthrough an integrated gpu since your main os “linux” requires them to boot your linux. And you will require an discrete gpu with its own output in order to work.

**Comment by hericiumvevo** [comment]
> There is no way you can passthrough an integrated gpu since your main os “linux” requires them to boot your linux. And you will require an discrete gpu with its own output in order to work.

After some research I discovered i can unload the Intel graphic driver, but that would require me to hack my cards BIOS and ROM and Im not into breaking my PC.

**Comment by rohankhanna** [comment]
Noob here. Does this seem possible if the host linux OS is running in cpu-only mode?

**Comment by Jerit3787** [comment]
> Noob here. Does this seem possible if the host linux OS is running in cpu-only mode?

it's not like you can't but if you run your linux in cpu-only mode you wouldn't see the desktop. besides, setting your linux to run cpu-only mode like in servers are already a hard one. Just like the one said before that I would need to hack your bios in order to able to passthrough your integrated gpu. Hopes this clarifies some of it.

**Comment by Jerit3787** [comment]
if this solves your issue, please do close this . Thanks in advance

**Comment by artforlife** [comment]
I have gone this path, but not all the way. What I have discovered is that it is theoretically possible. However, on my machine, the IOMMU groups were structured in a way that had the integrated GPU placed in the same group as all the other primary devices such as the chipset, controllers and others. 

Since passing through of devices works on a per-IOMMU-group basis, it means that the entire group of those devices would need to be passed. That is impossible since the host needs to retain control of those devices.

A possible solution to this is ASC-patching of the kernel. It basically creates a logical-level separation of devices and places them into different virtual IOMMU groups. However, it appears that there are some security and stability issues with that. Using ASC-patching is discouraged, though it is being included in some Linux distros by default. Aside from it being a pain-in-the-neck, it is these issues with ASC-patching that made me altogether abandon this approach and the entire project of trying to passthrough a lone integrated graphics card.
