### ISSUE TITLE
Update MacOS supported?

### ISSUE THREAD

**Issue by geckolinux** [foxlet/macOS-Simple-KVM#42]
Hi there, I wanted to ask about this statement:

https://passthroughpo.st/an-open-letter-to-linus-tech-tips-and-a-psa/
> No matter how successful the OS X setup process is, it will not be safe to update your VM. 

Does that mean that the native MacOS update process should not be used?

**Comment by foxlet** [comment]
For macOS-Simple-KVM it's generally safe to update as usual, but there's always a minor chance that a major version in the future will break for one reason or another.

The statement is in relation to bare metal and older VMs (the open letter is older than this). The biggest barrier to booting macOS is the SMC device, which only exists on the bus of real Macs. To pass it you can either inject custom code into the kernel (FakeSMC) or emulate it at a lower level (SMM, QEMU's SMC device).

Injecting, however, depends on the shim being able to patch the kernel, which in this case is Clover. Clover is known for breaking during kernel changes which is why updating older setups would be unsafe. Since we don't depend on Clover to emulate the SMC, it's not a problem.

**Comment by geckolinux** [comment]
Excellent, thanks for the comprehensive answer. This project is _seriously_ awesome, although I'm sure you already are aware of that. :-)
