### ISSUE TITLE
error: externally-managed-environment

### ISSUE THREAD

**Issue by rehmm070304** [foxlet/macOS-Simple-KVM#634]
When i run ./jumpstart.sh, I get this error...

`sdl@penguin:~/macOS-Simple-KVM$` ./jumpstart.sh --high-sierra
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
   If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
   If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
   See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Traceback (most recent call last):
  File "/home/sdl/macOS-Simple-KVM/tools/FetchMacOS/fetch-macos.py", line 9, in <module>
    import click
ModuleNotFoundError: No module named 'click'

**Comment by PinkSerenity** [comment]
The script wants to download a Python extension called `click`. It will try to download another one called `requests` as well. It doesn't work because the Python extension manager `pip` is disabled on your system. This is because you already have a package manager on your system and it's much cleaner and better for your projects as well as the OS to use that one to download extensions.

For `apt`:
`sudo apt install python3-click python3-requests`

**Comment by rehmm070304** [comment]
Thanks, this fixed the problem for me.
